language: cpp

script: ./travis-build.sh

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode10.3
